name: LogLyzer Production Build

on:
  push:
    branches: [main, master]
    paths:
      - "Client/**" # Only trigger if files in Client/ change
      - "Server/**" # Only trigger if files in Server/ change

jobs:
  client-build:
    name: Client Build & Test
    runs-on: [self-hosted, main]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Recommended LTS version
          cache: "npm"
          cache-dependency-path: Client/package-lock.json

      - name: Install Dependencies (Client)
        working-directory: ./Client
        run: npm ci

      - name: Lint Client Code
        working-directory: ./Client
        run: npm run lint

      - name: Build Client
        working-directory: ./Client
        run: npm run build

  server-build:
    name: Server Build & Test
    runs-on: [self-hosted, main]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
          cache-dependency-path: Server/package-lock.json

      - name: Install Dependencies (Server)
        working-directory: ./Server
        run: npm ci

      - name: Lint Server Code
        working-directory: ./Server
        run: npm run lint

      - name: Type Check Server
        working-directory: ./Server
        run: npm run ts.check

      - name: Build Server
        working-directory: ./Server
        run: npm run build

      - name: Restart Server using PM2
        working-directory: ./Server
        run: npx pm2 startOrReload pm2/ecosystem.config.json --env production
